global:
  scrape_interval: 30s # Интервал сбора метрик

scrape_configs:
  - job_name: 'blackbox'
    scrape_timeout: 25s  # Увеличение таймаута для запроса
    metrics_path: /probe
    params:
      module: [http_2xx]  # Модуль для HTTP проверок

    static_configs:
      - targets:
        - https://ptsecurity.com  # URL для мониторинга

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115  # Адрес Blackbox Exporter (проверьте, что он доступен)

