---
- name: Add PostgreSQL APT repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL APT repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt buster-pgdg main"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install PostgreSQL
  apt:
    name: postgresql-16
    state: present

- name: Start PostgreSQL service
  systemd:
    name: postgresql
    state: started
    enabled: yes

